version: "3.8"

services:
  mysqldb:
    platform: linux/arm64
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQLDB_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 30s
      retries: 1

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: online-book-store
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
